joint_limits:
  joint_shoulder_pan:
    has_acceleration_limits: true
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_acceleration: 5.0
    max_effort: 150.0
    max_position: 6.2831853
    max_velocity: 3.1415926
    min_position: -6.2831853
  joint_shoulder_lift:
    has_acceleration_limits: true
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_acceleration: 5.0
    max_effort: 150.0
    max_position: 6.2831853
    max_velocity: 3.14159265
    min_position: -6.2831853
  joint_elbow:
    has_acceleration_limits: true
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_acceleration: 5.0
    max_effort: 150.0
    max_position: 3.14159265
    max_velocity: 3.14159265
    min_position: -3.14159265
  joint_wrist_1:
    has_acceleration_limits: true
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_acceleration: 5.0
    max_effort: 28.0
    max_position: 6.2831853
    max_velocity: 3.14159265
    min_position: -6.2831853
  joint_wrist_2:
    has_acceleration_limits: true
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_acceleration: 5.0
    max_effort: 28.0
    max_position: 6.2831853
    max_velocity: 3.14159265
    min_position: -6.2831853
  joint_wrist_3:
    has_acceleration_limits: true
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_acceleration: 5.0
    max_effort: 28.0
    max_position: 6.2831853
    max_velocity: 3.14159265
    min_position: -6.2831853

  joint_plate_column:
    has_acceleration_limits: true
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_acceleration: 1.0
    max_effort: 400.0
    max_position: 0.3
    max_velocity: 1.0
    min_position: 0.0
  
  joint_gripper_left_knuckle:
    has_acceleration_limits: true
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_acceleration: 10.0
    max_effort: 50.0
    max_position: 0.8
    max_velocity: 0.5
    min_position: 0.0
