/**:
  controller_manager:
    ros__parameters:
      update_rate: 500  # Hz
    
      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster
      
      joint_trajectory_controller:
        type: joint_trajectory_controller/JointTrajectoryController
      
      scaled_joint_trajectory_controller:
        type: ur_controllers/ScaledJointTrajectoryController

      io_and_status_controller:
        type: ur_controllers/GPIOController

      speed_scaling_state_broadcaster:
        type: ur_controllers/SpeedScalingStateBroadcaster
      
      force_torque_sensor_broadcaster:
        type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster
      
      forward_velocity_controller:
        type: velocity_controllers/JointGroupVelocityController

      forward_position_controller:
        type: position_controllers/JointGroupPositionController
      
      force_mode_controller:
        type: ur_controllers/ForceModeController

      freedrive_mode_controller:
        type: ur_controllers/FreedriveModeController

      passthrough_trajectory_controller:
        type: ur_controllers/PassthroughTrajectoryController

      tcp_pose_broadcaster:
        type: pose_broadcaster/PoseBroadcaster

      ur_configuration_controller:
        type: ur_controllers/URConfigurationController

      tool_contact_controller:
        type: ur_controllers/ToolContactController

/**:
  joint_trajectory_controller:
    ros__parameters:
      joints:
        - joint_shoulder_pan
        - joint_shoulder_lift
        - joint_elbow
        - joint_wrist_1
        - joint_wrist_2
        - joint_wrist_3
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
      state_publish_rate: 100.0
      action_monitor_rate: 20.0
      allow_partial_joints_goal: false
      allow_integration_in_goal_trajectories: true
      start_with_holding: false
      allow_nonzero_velocity_at_trajectory_end: false
      interpolate_from_desired_state: true
      cmd_timeout: 0.0
      constraints:
        stopped_velocity_tolerance: 0.2
        goal_time: 0.0
        joint_shoulder_pan: { trajectory: 0.0, goal: 0.01 }
        joint_shoulder_lift: { trajectory: 0.0, goal: 0.01 }
        joint_elbow: { trajectory: 0.0, goal: 0.01 }
        joint_wrist_1: { trajectory: 0.0, goal: 0.01 }
        joint_wrist_2: { trajectory: 0.0, goal: 0.01 }
        joint_wrist_3: { trajectory: 0.0, goal: 0.01 }

/**:
  scaled_joint_trajectory_controller:
    ros__parameters:
      joints:
        - joint_shoulder_pan
        - joint_shoulder_lift
        - joint_elbow
        - joint_wrist_1
        - joint_wrist_2
        - joint_wrist_3
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
      state_publish_rate: 100.0
      action_monitor_rate: 20.0
      allow_partial_joints_goal: false
      allow_integration_in_goal_trajectories: true
      start_with_holding: false
      allow_nonzero_velocity_at_trajectory_end: false
      interpolate_from_desired_state: true
      cmd_timeout: 0.0
      constraints:
        stopped_velocity_tolerance: 0.2
        goal_time: 0.0
        joint_shoulder_pan: { trajectory: 0.0, goal: 0.01 }
        joint_shoulder_lift: { trajectory: 0.0, goal: 0.01 }
        joint_elbow: { trajectory: 0.0, goal: 0.01 }
        joint_wrist_1: { trajectory: 0.0, goal: 0.01 }
        joint_wrist_2: { trajectory: 0.0, goal: 0.01 }
        joint_wrist_3: { trajectory: 0.0, goal: 0.01 }
      speed_scaling_interface_name: speed_scaling/speed_scaling_factor

/**:
  speed_scaling_state_broadcaster:
    ros__parameters:
      state_publish_rate: 100.0
      tf_prefix: ""

/**:
  io_and_status_controller:
    ros__parameters:
      tf_prefix: ""

/**:
  ur_configuration_controller:
    ros__parameters:
      tf_prefix: ""

/**:
  force_torque_sensor_broadcaster:
    ros__parameters:
      sensor_name: tcp_fts_sensor
      state_interface_names:
        - force.x
        - force.y
        - force.z
        - torque.x
        - torque.y
        - torque.z
      frame_id: link_tool0
      topic_name: ft_data

/**:
  tcp_pose_broadcaster:
    ros__parameters:
      frame_id: link_base
      pose_name: tcp_pose
      tf:
        child_frame_id: link_tool0

/**:
  passthrough_trajectory_controller:
    ros__parameters:
      tf_prefix: ""
      joints:
        - joint_shoulder_pan
        - joint_shoulder_lift
        - joint_elbow
        - joint_wrist_1
        - joint_wrist_2
        - joint_wrist_3
      state_interfaces:
        - position
        - velocity
      speed_scaling_interface_name: speed_scaling/speed_scaling_factor

/**:
  forward_velocity_controller:
    ros__parameters:
      joints:
        - joint_shoulder_pan
        - joint_shoulder_lift
        - joint_elbow
        - joint_wrist_1
        - joint_wrist_2
        - joint_wrist_3
      interface_name: velocity

/**:
  forward_position_controller:
    ros__parameters:
      joints:
        - joint_shoulder_pan
        - joint_shoulder_lift
        - joint_elbow
        - joint_wrist_1
        - joint_wrist_2
        - joint_wrist_3

/**:
  force_mode_controller:
    ros__parameters:
      tf_prefix: ""

/**:
  freedrive_mode_controller:
    ros__parameters:
      tf_prefix: ""

/**:
  tool_contact_controller:
    ros__parameters:
      tf_prefix: ""
