robot_ip: 192.168.0.11  # The robot's IP address.

script_filename: /opt/ros/jazzy/share/ur_client_library/resources/external_control.urscript # Path to the urscript code that will be sent to the robot.
output_recipe_filename: /opt/ros/jazzy/share/ur_robot_driver/resources/rtde_output_recipe.txt  # Path to the file containing the recipe used for requesting RTDE outputs.
input_recipe_filename: /opt/ros/jazzy/share/ur_robot_driver/resources/rtde_input_recipe.txt  # Path to the file containing the recipe used for requesting RTDE inputs.

headless_mode: false  # Start robot in headless mode. 
                      # This does not require the 'External Control' URCap to be running on the robot, 
                      # but this will send the URScript to the robot directly. 
                      # On e-Series robots this requires the robot to run in 'remote-control' mode.
joint_controller_active: false

reverse_ip: 0.0.0.0
script_command_port: 50004
reverse_port: 50001  # Port that will be opened to communicate between the driver and the robot controller.
script_sender_port: 50002  # Network port which the driver provides the URScript program that needs to run on the robot. 
                           # This number needs to be configured for the [External Control URCap](https://github.com/UniversalRobots/Universal_Robots_ExternalControl_URCap). 
                           # This port needs to be free and will be opened on the host running the driver.
trajectory_port: 50003

use_tool_communication: false
tool_voltage: 0
tool_parity: 0  # Parity used for tool communication. Will be set as soon as the UR-Program on the robot is started. Can be 0 (None), 1 (odd) and 2 (even). Note: This parameter is only evaluated, when the parameter “use_tool_communication” is set to true. Then, this parameter is required.
                # This can also be configured using the robot teach pendant. Remember to save the installation on the robot to keep the setting after reboot.
tool_baud_rate: 115200  # Baud rate used for tool communication. 
                        # Will be set as soon as the UR-Program on the robot is started. 
                        # See UR documentation for valid baud rates.  
                        # Note: This parameter is only evaluated, when the parameter "use_tool_communication" is set to TRUE. Then, this parameter is required.
tool_stop_bits: 1
tool_rx_idle_chars: 1.5
tool_tx_idle_chars: 3.5
tool_device_name: /tmp/ttyUR
tool_tcp_port: 54321

non_blocking_read: true  # If set to false, the ROS control cycle will wait for the robot to send a status update. 
                         # Tests have shown that better real-time performance is achievable when setting this to true. 
                         # Required to be set to true when combining with other hardware components.

servoj_gain: 2000  # Specify the gain for the underlying servoj command. 
                   # This will be used whenever position control is active. 
                   # A higher value will lead to sharper motions, but might also introduce higher jerks and vibrations.
servoj_lookahead_time: 0.03  # Specify lookahead_time parameter of underlying servoj command. 
                             # This will be used whenever position control is active. 
                             # A higher value will result in smoother trajectories, but will also introduce a higher delay between the commands sent from ROS and the motion being executed on the robot.
robot_receive_timeout: 0.04  # Timeout for the robot to respond to a command. 
                             # This is used to prevent the robot from hanging if it does not respond to a command. 
                             # Must be a multiple of 0.02